name: sync-fork
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: { }

# TODO: Array of forks
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          [ 'derskythe/flipperzero-subbrute', 'derskythe/libuv', 'derskythe/mlib', 'derskythe/emv-utils' ]
        include:
          - repo: 'derskythe/flipperzero-subbrute'
            branch: 'master'
          - repo: 'derskythe/libuv'
            branch: 'v1.x'
          - repo: 'derskythe/mlib'
            branch: 'master'
          - repo: 'derskythe/emv-utils'
            branch: 'master'
    permissions:
      contents: write
    steps:
      - run: gh repo sync ${{ matrix.repo }} -b ${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
