name: sync-fork
run-name: 'Auto sync fork repositories by the event ${{ github.event_name }}'
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: { }
  push:
    branches: master
    paths:
      - '.github/workflows/auto-sync-fork.yaml'

# TODO: Array of forks
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - 'derskythe/flipperzero-subbrute' 
          - 'derskythe/libuv'
          - 'derskythe/mlib' 
          - 'derskythe/emv-utils'
          - 'derskythe/IOTstack'
          - 'derskythe/SoapCore'
          - 'derskythe/flipperzero-firmware-derskythe'
          - 'derskythe/all-the-plugins'
          - 'derskythe/Flipper'
          - 'derskythe/flipperzero-firmware'
          - 'derskythe/awesome-flipperzero'
          - 'derskythe/flipper-zero-fap-boilerplate'
          - 'derskythe/FZEasyMarauderFlash'
          - 'derskythe/totp-manager-dotnetcore'
          - 'derskythe/OBD.NET'
          - 'derskythe/zerotier-docker'
          - 'derskythe/dotnet-document'
        include:
          - repo: 'derskythe/flipperzero-subbrute'
            branch: 'master'
          - repo: 'derskythe/libuv'
            branch: 'v1.x'
          - repo: 'derskythe/mlib'
            branch: 'master'
          - repo: 'derskythe/emv-utils'
            branch: 'master'
          - repo: 'derskythe/IOTstack'
            branch: 'master'
          - repo: 'derskythe/SoapCore'
            branch: 'master'
          - name: 'derskythe/flipperzero-firmware-derskythe'
            branch: 'custom'
          - name: 'derskythe/all-the-plugins'
            branch: 'dev'
          - name: 'derskythe/Flipper'
            branch: 'master'
          - name: 'derskythe/flipperzero-firmware'
            branch: 'dev'
          - name: 'derskythe/awesome-flipperzero'
            branch: 'master'
          - name: 'derskythe/flipper-zero-fap-boilerplate'
            branch: 'master'
          - name: 'derskythe/FZEasyMarauderFlash'
            branch: 'master'
          - name: 'derskythe/totp-manager-dotnetcore'
            branch: 'master'
          - name: 'derskythe/OBD.NET'
            branch: 'master'
          - name: 'derskythe/zerotier-docker'
            branch: 'master'
          - name: 'derskythe/dotnet-document'
            branch: 'master'
    permissions:
      contents: write
    steps:
      - run: gh repo sync ${{ matrix.repo }} -b ${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
