# https://github.com/lowlighter/metrics
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          retries: 3
          retries_delay: 300
          optimize: css, xml
          use_prebuilt_image: yes
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: master
          config_timezone: Asia/Baku
          config_twemoji: true
          clean_workflows: failure, cancelled, startup_failure, timed_out
          verify: true
          # To check 
          # plugins_errors_fatal: true
          # debug: true
          # debug_print: true
          config_order: base.header, isocalendar, languages, stars, lines, base.repositories, habits, starlists, people, reactions, base.activity+community, followup, 
          #base: header,activity,repositories,metadata,community
          #base: header,activity,repositories,community
          base_indepth: true
          base_hireable: true
          repositories_affiliations: owner,collaborator,organization_member
          token: ${{ secrets.METRICS_TOKEN }}
          #template: repository
          template: classic
          user: derskythe
          repo: derskythe
          # Topics
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_topics_limit: 30
          # Lines
          plugin_lines: yes
          plugin_lines_history_limit: 355
          plugin_lines_delay: 120
          # Followp
          plugin_followup: yes
          # ISO Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # Languages
          plugin_languages: yes
          # StarGazers
          # plugin_stargazers: yes
          # plugin_stargazers_charts: yes
          # plugin_stargazers_charts_type: graph
          # Recently stared
          plugin_stars: yes
          plugin_stars_limit: 10
          # Habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_trim: true
          # Reactions
          plugin_reactions: true
          # People
          plugin_people: yes
          plugin_people_identicons: yes
          plugin_people_types: followers,following
          # Featured repositaries
          plugin_repositories: yes
          plugin_repositories_order: starred
          # Star list
          plugin_starlists: yes
          plugin_starlists_limit: 10
          plugin_starlists_limit_repositories: 10
          # Calendar
          plugin_calendar: yes
          plugin_calendar_limit: 2
          # Intoduction
          plugin_introduction: yes
